version: '3.3'
services:
  server: 
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    command: npm run dev
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      NODE_ENV : docker

  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    stdin_open: true    
    command: npm start
    ports:
        - target: 3000
          published: 4960
          protocol: tcp
          mode: host
  postgres:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432" 
    environment:
        POSTGRES_USER: ctp_user
        POSTGRES_PASSWORD: ctp_pass
        POSTGRES_DB: app2020_docker
    