version: '3.3'
services:

  postgres:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432" 
    environment:
        POSTGRES_USER: ctp_user
        POSTGRES_PASSWORD: ctp_pass
        POSTGRES_DB: app2020_docker

  server: 
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    volumes: 
      - './api:/usr/app/api'
      - /usr/app/node_modules/
    command: npm run docker_dev
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
    environment:
      PORT: 8000
      NODE_ENV: "docker"
      CHOKIDAR_USEPOLLING: "true"

  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    stdin_open: true    
    volumes: 
      - './client:/app/'
      - /app/node_modules/
    command: npm start
    depends_on: 
      - server
    ports:
        - target: 3000
          published: 4960
          protocol: tcp
          mode: host
    environment:
      PROXY: "http://server:8000"
      CHOKIDAR_USEPOLLING: "true"
